version: '3'

services:
  php:
    image: php:latest
    volumes:
      - ../:/var/www/app
      - ./php/config:/usr/local/etc/php/conf.d
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - DATABASE_URL=mysql://myuser:mypassword@mariadb:3307/mydatabase
    build:
      context: ./php
    depends_on:
      - mariadb
    #networks:
    #  - default
    restart: always

  apache:
    image: httpd:latest
    volumes:
      - ../:/var/www/app
      - ./apache/config:/usr/local/apache2/conf.d
      - ./apache/logs/:/var/log/apache2
    ports:
      - "8085:80"
    build:
      context: ./apache
    depends_on:
      - php
    networks:
      - default

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3310:3306"
    networks:
      - default
      
  redpanda:
    entrypoint:
      - /usr/bin/rpk
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29097,OUTSIDE://0.0.0.0:9097
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29097,OUTSIDE://redpanda:9097
      - --check=false
    image: redpandadata/redpanda:latest
    ports:
      - 9097:9097
      - 29097:29097
    volumes:
      - ./redpanda/config:/usr/local/etc/redpanda
      - ./redpanda/logs:/var/log/redpanda
    networks:
      - default